FROM java:8-jre
MAINTAINER Kyle Williamson <kyle.d.m.williamson@gmail.com>

ADD ./maintenance-organisation-service-0.0.1.jar /app/
CMD ["java", "-Xmx200m", "-jar", "/app/maintenance-organisation-service-0.0.1.jar"]

EXPOSE 8408
