server.port: 8406

hystrix:
 threadpool.default.coreSize: "20"
 threadpool.default.maxQueueSize: "500000"
 threadpool.default.keepAliveTimeMinutes: "2"
 threadpool.default.queueSizeRejectionThreshold: "500000"
 command:
   default:
     fallback.isolation.semaphore.maxConcurrentRequests: "20"
     execution:
       timeout:
         enabled: "false"
       isolation:
         strategy: "THREAD"
         thread:
           timeoutInMilliseconds: "30000"

eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery-service:8101/eureka

amazon:
  dynamodb:
    endpoint: http://dynamodb.eu-west-1.amazonaws.com/
  aws:
    accesskey: AKIAJ6HL5CWG4TPJK4EQ
    secretkey: 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
spring:
  rabbitmq:
    host: rabbitmq