package com.kyle.ie.property_appliance.models;

import java.util.ArrayList;
import java.util.List;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "PropertyAppliance")
public class PropertyAppliance {
	
	private String _id;

	private String _applianceId;
	private String _statusId;
	private String _propertyId;
	
	private String _name;
	private int _age;

	private List<StatusHistory> _statusHistory;
	
	public PropertyAppliance() {}

	@Id
	@DynamoDBHashKey(attributeName = "propApplId")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return _id;
	}

	public void setId(String id) {
		this._id = id;
	}
	
	@DynamoDBAttribute
	public String getApplianceId() {
		return _applianceId;
	}

	public void setApplianceId(String applianceId) {
		this._applianceId = applianceId;
	}

	@DynamoDBAttribute
	public String getStatusId() {
		return _statusId;
	}

	public void setStatusId(String statusId) {
		this._statusId = statusId;
	}

	@DynamoDBAttribute
	public String getPropertyId() {
		return _propertyId;
	}

	public void setPropertyId(String propertyId) {
		this._propertyId = propertyId;
	}

	@DynamoDBAttribute
	public String getName() {
		return _name;
	}

	public void setName(String name) {
		this._name = name;
	}

	@DynamoDBAttribute
	public int getAge() {
		return _age;
	}

	public void setAge(int age) {
		this._age = age;
	}

	@DynamoDBAttribute
	public List<StatusHistory> getStatusHistory() {
		if(_statusHistory == null) {
			_statusHistory = new ArrayList<>();
		}
		return _statusHistory;
	}

	public void setStatusHistory(List<StatusHistory> statusHistory) {
		this._statusHistory = statusHistory;
	}
}
