FROM java:8-jre
MAINTAINER Kyle Williamson <kyle.d.m.williamson@gmail.com>

ADD ./analytics-web-portal-service-0.0.1.jar /app/
CMD ["java", "-Xmx200m", "-jar", "/app/analytics-web-portal-service-0.0.1.jar"]

EXPOSE 8500
