package com.kyle.ie.report.diagnostic.models;

import java.util.List;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "DiagnosticReport")
public class DiagnosticReport {
	
	@Id
	@DynamoDBHashKey(attributeName = "diagRepId")
	@DynamoDBAutoGeneratedKey
	private String id;
	
	private String propApplId;
	
	private int managerId;
	
	private List<String> organisations;

	private int timestamp;
	private String description;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getPropApplId() {
		return propApplId;
	}
	public void setPropApplId(String propApplId) {
		this.propApplId = propApplId;
	}

	@DynamoDBAttribute
	public int getTimestamp() {
		return timestamp;
	}
	public void setTimestamp(int timestamp) {
		this.timestamp = timestamp;
	}

	@DynamoDBAttribute
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}

	@DynamoDBAttribute
	public int getManagerId() {
		return managerId;
	}
	public void setManagerId(int managerId) {
		this.managerId = managerId;
	}

	@DynamoDBAttribute
	public List<String> getOrganisations() {
		return organisations;
	}
	public void setOrganisations(List<String> organisations) {
		this.organisations = organisations;
	}
	
}
