package com.kyle.ie.maintenance.models;

import java.util.List;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "MaintenanceOrganisation")
public class MaintenanceOrganisation {

	private String id;
	private List<Integer> engineers;
	private List<String> pendingDiagnosticReports;
	private List<String> respondedDiagnosticReports;
	
	@Id
	@DynamoDBHashKey(attributeName = "orgId")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public List<Integer> getEngineers() {
		return engineers;
	}
	public void setEngineers(List<Integer> engineers) {
		this.engineers = engineers;
	}

	@DynamoDBAttribute
	public List<String> getPendingDiagnosticReports() {
		return pendingDiagnosticReports;
	}
	public void setPendingDiagnosticReports(List<String> pendingDiagnosticReports) {
		this.pendingDiagnosticReports = pendingDiagnosticReports;
	}

	@DynamoDBAttribute
	public List<String> getRespondedDiagnosticReports() {
		return respondedDiagnosticReports;
	}
	public void setRespondedDiagnosticReports(List<String> respondedDiagnosticReports) {
		this.respondedDiagnosticReports = respondedDiagnosticReports;
	}
	
	
}
