package com.kyle.ie.appliance.models;

import java.util.List;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.kyle.ie.appliance.marshaller.EnumMarshaller;
import com.kyle.ie.appliance.models.constants.ApplianceType;
import com.kyle.ie.appliance.models.constants.ClimateClass;
import com.kyle.ie.appliance.models.constants.ConstructionType;
import com.kyle.ie.appliance.models.constants.ControlType;
import com.kyle.ie.appliance.models.constants.CoolingAgent;
import com.kyle.ie.appliance.models.constants.DoorType;
import com.kyle.ie.appliance.models.constants.DryingPerformanceClass;
import com.kyle.ie.appliance.models.constants.EnergyRating;
import com.kyle.ie.appliance.models.constants.FitType;
import com.kyle.ie.appliance.models.constants.GrillType;
import com.kyle.ie.appliance.models.constants.LoadingType;
import com.kyle.ie.appliance.models.constants.PowerSource;
import com.kyle.ie.appliance.models.constants.WashingPerformanceClass;


@DynamoDBTable(tableName = "Appliance")
public class Appliance {

	@Id
	@DynamoDBHashKey(attributeName = "applId")
	@DynamoDBAutoGeneratedKey
	private String id;

	private String productNo;
	private String name;
	private String brand;
	private ApplianceType type;
	private List<String> features;

	// mm
	private double width;
	private double height;
	private double depth;

	// kg
	private double weight;
	
	private ApplianceImage applianceImage;
	

	private int placeSettings;
	private int presetCycles;

	private boolean delayStart;
	private boolean antiFloodProtection;

	// db
	private int noiseLevel;

	private ControlType controlType;
	
	private boolean interiorLight;
	private boolean lcd;
	private boolean led;

	// litres
	private int annualWaterConsumption;

	// kwh
	private int annualEnergyConsumption;

	// Hz
	private int frequency;

	// V
	private int voltageMin;
	private int voltageMax;

	private DryingPerformanceClass dryingPerformanceClass;
	private WashingPerformanceClass washingPerformanceClass;
	private EnergyRating energyRating;

	private FitType fitType;

	private int fridgePercentage;
	private int freezerPercentage;

	private boolean waterDispenser;
	private boolean autoDefrost;

	private ClimateClass climateClass;

	private int noOfCompressors;

	// hours
	private int powerFailureSafeStorageTime;

	// litres
	private int fridgeCapacity;

	private int fridgeShelves;

	private boolean fastFreeze;

	// kg
	private int freezingCapacity;

	// litre
	private int freezerCapacity;

	private int freezerShelves;
	private boolean frostFree;

	private DoorType doorType;

	private int noOfDoors;

	private List<String> approvedCertifications;

	private boolean plumbed;
	
	private CoolingAgent coolingAgent;

	//litres
	private double capacity;
	
	private boolean defrostFunction;

	private String cavitySurfaceMaterial;
	
	// W
	private int power;
	
	private int powerLevelNo;
	private int grillPower;
	
	//mm
	private double turntableSize;
	
	private int autoFunctions;

	private int noOfOvens;

	private boolean singleOven;
	private boolean doubleOven;

	private ConstructionType constructionType;
	private String fuelType;

	private List<String> cleaning;

	private boolean interiorLights;

	private boolean autoShutOff;

	// A
	private double electricalConnection;

	private PowerSource powerSource;

	private GrillType grillType;

	private int noOfFunctions;

	private boolean vented;
	private boolean condensed;

	// kg
	private int dryerCapacity;

	// db
	private int spinNoiseLevel;

	private boolean inbuiltHome;

	private int numberOfProgrammes;

	private LoadingType loadingType;

	// db
	private int washNoiseLevel;

	private boolean quickWash;

	private boolean inBuiltHeater;

	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public String getProductNo() {
		return productNo;
	}

	public void setProductNo(String productNo) {
		this.productNo = productNo;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public ApplianceType getType() {
		return type;
	}

	public void setType(ApplianceType type) {
		this.type = type;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public List<String> getFeatures() {
		return features;
	}

	public void setFeatures(List<String> features) {
		this.features = features;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public double getWidth() {
		return width;
	}

	public void setWidth(double width) {
		this.width = width;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public double getHeight() {
		return height;
	}

	public void setHeight(double height) {
		this.height = height;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public double getDepth() {
		return depth;
	}

	public void setDepth(double depth) {
		this.depth = depth;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public double getWeight() {
		return weight;
	}

	public void setWeight(double weight) {
		this.weight = weight;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public ApplianceImage getApplianceImage() {
		return applianceImage;
	}

	public void setApplianceImage(ApplianceImage image) {
		this.applianceImage = image;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getPlaceSettings() {
		return placeSettings;
	}

	public void setPlaceSettings(int placeSettings) {
		this.placeSettings = placeSettings;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getPresetCycles() {
		return presetCycles;
	}

	public void setPresetCycles(int presetCycles) {
		this.presetCycles = presetCycles;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getDelayStart() {
		return delayStart;
	}

	public void setDelayStart(boolean delayStart) {
		this.delayStart = delayStart;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getAntiFloodProtection() {
		return antiFloodProtection;
	}

	public void setAntiFloodProtection(boolean antiFloodProtection) {
		this.antiFloodProtection = antiFloodProtection;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getNoiseLevel() {
		return noiseLevel;
	}

	public void setNoiseLevel(int noiseLevel) {
		this.noiseLevel = noiseLevel;
	}

	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public ControlType getControlType() {
		return controlType;
	}

	public void setControlType(ControlType controlType) {
		this.controlType = controlType;
	}
	
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getInteriorLight() {
		return interiorLight;
	}

	public void setInteriorLight(boolean interiorLight) {
		this.interiorLight = interiorLight;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getLcd() {
		return lcd;
	}

	public void setLcd(boolean lcd) {
		this.lcd = lcd;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getLed() {
		return led;
	}

	public void setLed(boolean led) {
		this.led = led;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getAnnualWaterConsumption() {
		return annualWaterConsumption;
	}

	public void setAnnualWaterConsumption(int annualWaterConsumption) {
		this.annualWaterConsumption = annualWaterConsumption;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getAnnualEnergyConsumption() {
		return annualEnergyConsumption;
	}

	public void setAnnualEnergyConsumption(int annualEnergyConsumption) {
		this.annualEnergyConsumption = annualEnergyConsumption;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getFrequency() {
		return frequency;
	}

	public void setFrequency(int frequency) {
		this.frequency = frequency;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getVoltageMin() {
		return voltageMin;
	}

	public void setVoltageMin(int voltageMin) {
		this.voltageMin = voltageMin;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getVoltageMax() {
		return voltageMax;
	}

	public void setVoltageMax(int voltageMax) {
		this.voltageMax = voltageMax;
	}

	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public DryingPerformanceClass getDryingPerformanceClass() {
		return dryingPerformanceClass;
	}

	public void setDryingPerformanceClass(DryingPerformanceClass dryingPerformanceClass) {
		this.dryingPerformanceClass = dryingPerformanceClass;
	}
	
	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public WashingPerformanceClass getWashingPerformanceClass() {
		return washingPerformanceClass;
	}

	public void setWashingPerformanceClass(WashingPerformanceClass washingPerformanceClass) {
		this.washingPerformanceClass = washingPerformanceClass;
	}
	
	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public EnergyRating getEnergyRating() {
		return energyRating;
	}

	public void setEnergyRating(EnergyRating energyRating) {
		this.energyRating = energyRating;
	}

	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public FitType getFitType() {
		return fitType;
	}

	public void setFitType(FitType fitType) {
		this.fitType = fitType;
	}
	
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getFridgePercentage() {
		return fridgePercentage;
	}

	public void setFridgePercentage(int fridgePercentage) {
		this.fridgePercentage = fridgePercentage;
	}
	
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getFreezerPercentage() {
		return freezerPercentage;
	}

	public void setFreezerPercentage(int freezerPercentage) {
		this.freezerPercentage = freezerPercentage;
	}
	
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getWaterDispenser() {
		return waterDispenser;
	}

	public void setWaterDispenser(boolean waterDispenser) {
		this.waterDispenser = waterDispenser;
	}

	public boolean getAutoDefrost() {
		return autoDefrost;
	}

	public void setAutoDefrost(boolean autoDefrost) {
		this.autoDefrost = autoDefrost;
	}

	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public ClimateClass getClimateClass() {
		return climateClass;
	}

	public void setClimateClass(ClimateClass climateClass) {
		this.climateClass = climateClass;
	}
	
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getNoOfCompressors() {
		return noOfCompressors;
	}

	public void setNoOfCompressors(int noOfCompressors) {
		this.noOfCompressors = noOfCompressors;
	}
	
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getPowerFailureSafeStorageTime() {
		return powerFailureSafeStorageTime;
	}

	public void setPowerFailureSafeStorageTime(int powerFailureSafeStorageTime) {
		this.powerFailureSafeStorageTime = powerFailureSafeStorageTime;
	}
	
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getFridgeCapacity() {
		return fridgeCapacity;
	}

	public void setFridgeCapacity(int fridgeCapacity) {
		this.fridgeCapacity = fridgeCapacity;
	}
	
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getFridgeShelves() {
		return fridgeShelves;
	}

	public void setFridgeShelves(int fridgeShelves) {
		this.fridgeShelves = fridgeShelves;
	}
	
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getFastFreeze() {
		return fastFreeze;
	}

	public void setFastFreeze(boolean fastFreeze) {
		this.fastFreeze = fastFreeze;
	}
	
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getFreezingCapacity() {
		return freezingCapacity;
	}

	public void setFreezingCapacity(int freezingCapacity) {
		this.freezingCapacity = freezingCapacity;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getFreezerCapacity() {
		return freezerCapacity;
	}

	public void setFreezerCapacity(int freezerCapacity) {
		this.freezerCapacity = freezerCapacity;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getFreezerShelves() {
		return freezerShelves;
	}

	public void setFreezerShelves(int freezerShelves) {
		this.freezerShelves = freezerShelves;
	}
	
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean isFrostFree() {
		return frostFree;
	}

	public void setFrostFree(boolean frostFree) {
		this.frostFree = frostFree;
	}

	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public DoorType getDoorType() {
		return doorType;
	}

	public void setDoorType(DoorType doorType) {
		this.doorType = doorType;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getNoOfDoors() {
		return noOfDoors;
	}

	public void setNoOfDoors(int noOfDoors) {
		this.noOfDoors = noOfDoors;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public List<String> getApprovedCertifications() {
		return approvedCertifications;
	}

	public void setApprovedCertifications(List<String> approvedCertifications) {
		this.approvedCertifications = approvedCertifications;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getPlumbed() {
		return plumbed;
	}

	public void setPlumbed(boolean plumbed) {
		this.plumbed = plumbed;
	}

	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public CoolingAgent getCoolingAgent() {
		return coolingAgent;
	}

	public void setCoolingAgent(CoolingAgent coolingAgent) {
		this.coolingAgent = coolingAgent;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public double getCapacity() {
		return capacity;
	}

	public void setCapacity(double capacity) {
		this.capacity = capacity;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getDefrostFunction() {
		return defrostFunction;
	}

	public void setDefrostFunction(boolean defrostFunction) {
		this.defrostFunction = defrostFunction;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public String getCavitySurfaceMaterial() {
		return cavitySurfaceMaterial;
	}

	public void setCavitySurfaceMaterial(String cavitySurfaceMaterial) {
		this.cavitySurfaceMaterial = cavitySurfaceMaterial;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getPower() {
		return power;
	}

	public void setPower(int power) {
		this.power = power;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getPowerLevelNo() {
		return powerLevelNo;
	}

	public void setPowerLevelNo(int powerLevelNo) {
		this.powerLevelNo = powerLevelNo;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getGrillPower() {
		return grillPower;
	}

	public void setGrillPower(int grillPower) {
		this.grillPower = grillPower;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public double getTurntableSize() {
		return turntableSize;
	}

	public void setTurntableSize(double turntableSize) {
		this.turntableSize = turntableSize;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getAutoFunctions() {
		return autoFunctions;
	}

	public void setAutoFunctions(int autoFunctions) {
		this.autoFunctions = autoFunctions;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getNoOfOvens() {
		return noOfOvens;
	}

	public void setNoOfOvens(int noOfOvens) {
		this.noOfOvens = noOfOvens;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getSingleOven() {
		return singleOven;
	}

	public void setSingleOven(boolean singleOven) {
		this.singleOven = singleOven;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getDoubleOven() {
		return doubleOven;
	}

	public void setDoubleOven(boolean doubleOven) {
		this.doubleOven = doubleOven;
	}

	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public ConstructionType getConstructionType() {
		return constructionType;
	}

	public void setConstructionType(ConstructionType constructionType) {
		this.constructionType = constructionType;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public String getFuelType() {
		return fuelType;
	}

	public void setFuelType(String fuelType) {
		this.fuelType = fuelType;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public List<String> getCleaning() {
		return cleaning;
	}

	public void setCleaning(List<String> cleaning) {
		this.cleaning = cleaning;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getInteriorLights() {
		return interiorLights;
	}

	public void setInteriorLights(boolean interiorLights) {
		this.interiorLights = interiorLights;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getAutoShutOff() {
		return autoShutOff;
	}

	public void setAutoShutOff(boolean autoShutOff) {
		this.autoShutOff = autoShutOff;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public double getElectricalConnection() {
		return electricalConnection;
	}

	public void setElectricalConnection(double electricalConnection) {
		this.electricalConnection = electricalConnection;
	}

	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public PowerSource getPowerSource() {
		return powerSource;
	}

	public void setPowerSource(PowerSource powerSource) {
		this.powerSource = powerSource;
	}

	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public GrillType getGrillType() {
		return grillType;
	}

	public void setGrillType(GrillType grillType) {
		this.grillType = grillType;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getNoOfFunctions() {
		return noOfFunctions;
	}

	public void setNoOfFunctions(int noOfFunctions) {
		this.noOfFunctions = noOfFunctions;
	}
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getVented() {
		return vented;
	}

	public void setVented(boolean vented) {
		this.vented = vented;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getCondensed() {
		return condensed;
	}

	public void setCondensed(boolean condensed) {
		this.condensed = condensed;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getDryerCapacity() {
		return dryerCapacity;
	}

	public void setDryerCapacity(int dryerCapacity) {
		this.dryerCapacity = dryerCapacity;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getSpinNoiseLevel() {
		return spinNoiseLevel;
	}

	public void setSpinNoiseLevel(int spinNoiseLevel) {
		this.spinNoiseLevel = spinNoiseLevel;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getInbuiltHome() {
		return inbuiltHome;
	}

	public void setInbuiltHome(boolean inbuiltHome) {
		this.inbuiltHome = inbuiltHome;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getNumberOfProgrammes() {
		return numberOfProgrammes;
	}

	public void setNumberOfProgrammes(int numberOfProgrammes) {
		this.numberOfProgrammes = numberOfProgrammes;
	}

	@DynamoDBMarshalling(marshallerClass=EnumMarshaller.class)
	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public LoadingType getLoadingType() {
		return loadingType;
	}

	public void setLoadingType(LoadingType loadingType) {
		this.loadingType = loadingType;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public int getWashNoiseLevel() {
		return washNoiseLevel;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public void setWashNoiseLevel(int washNoiseLevel) {
		this.washNoiseLevel = washNoiseLevel;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getQuickWash() {
		return quickWash;
	}

	public void setQuickWash(boolean quickWash) {
		this.quickWash = quickWash;
	}

	@DynamoDBAttribute
	@JsonInclude(Include.NON_DEFAULT)
	public boolean getInBuiltHeater() {
		return inBuiltHeater;
	}

	public void setInBuiltHeater(boolean inBuiltHeater) {
		this.inBuiltHeater = inBuiltHeater;
	}

}
